# Generated by Django 4.2.6 on 2024-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='picture',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
