# Generated by Django 4.2.6 on 2024-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mobiles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='picture',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
